services:
  nginx:
    build: ./nginx
    container_name: reverse_proxy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
    depends_on:
      - api_gateway

  api_gateway:
    build: ./api_gateway
    container_name: api_gateway
    environment:
      DOMAINS_URL: ${DOMAINS_URL}
    expose:
      - "8000"
    depends_on:
      - domains_api

  domains_api:
    build: ./domains
    container_name: domains_api
    env_file:
      - .env
    environment:
      REDIS_HOST: ${XPOSED_OR_NOT_REDIS_HOST}
      REDIS_PORT: ${XPOSED_OR_NOT_REDIS_PORT}
      POSTGRES_USER: ${XPOSED_OR_NOT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${XPOSED_OR_NOT_POSTGRES_PASSWORD}
      POSTGRES_DB: ${XPOSED_OR_NOT_POSTGRES_DB}
      POSTGRES_HOST: ${XPOSED_OR_NOT_POSTGRES_HOST}
      POSTGRES_PORT: ${XPOSED_OR_NOT_POSTGRES_PORT}
    depends_on:
      - redis
    expose:
      - "5000"
    ports:
      - "9100:5000" # optional: keep for debugging

  redis:
    image: redis:7
    container_name: my_redis
    command:
      - redis-server
      - --maxmemory 300mb
      - --maxmemory-policy allkeys-lru
      - --appendonly no
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # frontend:
  #   build:
  #     context: ./frontend_cyber
  #     dockerfile: Dockerfile
  #     args:
  #       VITE_API_URL: http://localhost
  #   container_name: xposed_or_not_frontend
  #   ports:
  #     - "5173:5173"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # main protocol
      - "15672:15672" # management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

volumes:
  redis_data: {}
